name: kazumi
publish_to: none
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  dio: ^5.11.0
  html: ^0.15.6
  json_path: ^0.9.0
  xpath_selector_html_parser: ^3.0.1
dev_dependencies:
  test: ^1.25.0
